spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB
  messages:
    basename: messages/messages
    encoding: UTF-8
  datasource:
    url: jdbc:sqlite:C:/Users/phy/AppData/Roaming/DBeaverData/workspace6/.metadata/sample-database-sqlite-1/Chinook.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.backend.domain
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

decorator:
  datasource:
    datasource-proxy:
      logging: slf4j
      query:
        enable-logging: false  #enable-logging: true
        # log-level: info
      multiline: false

app:
  file-storage:
    root-path: ${user.home}/.jpa-file-storage

logging:
  file:
    path: logs
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
    org.hibernate.type.descriptor.sql: warn
    jdbc.sql: info
    #net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener: info
